# Generated by Django 2.2.15 on 2020-08-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='If the entry is active or soft deleted')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('baseformodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.BaseForModels')),
                ('title', models.CharField(help_text='Title of the product', max_length=64)),
                ('description', models.TextField(help_text='Description of the product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=6)),
                ('image', models.URLField(blank=True, help_text='Image for the product', null=True)),
                ('stock', models.IntegerField(blank=True, help_text='Stock available for the product', null=True)),
            ],
            options={
                'get_latest_by': 'created_at',
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
            bases=('products.baseformodels',),
        ),
    ]
