# Generated by Django 2.2.15 on 2020-08-08 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200808_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='If the entry is active or soft deleted')),
                ('name', models.CharField(help_text='Name for the promotion rule', max_length=100)),
                ('start_from', models.DateTimeField(help_text='Promotion starting on date and time')),
                ('end_by', models.DateTimeField(blank=True, help_text='Promotion ending on date and time', null=True)),
                ('disable', models.BooleanField(default=False, help_text='True if promotion is stopped')),
                ('promotion_for', models.CharField(choices=[('cart', 'Cart'), ('product', 'Product')], help_text='Promotion for cart or product', max_length=100)),
                ('promotion_type', models.CharField(choices=[('discount_percentage', 'Discount Percentage'), ('fixed_amount', 'Fixed Amount')], help_text='Type of promotion', max_length=100)),
                ('promotion_on', models.CharField(choices=[('single_product', 'Single Product'), ('multiple_product', 'Multiple Product')], help_text='Promotion for single or multiple products', max_length=100)),
                ('discount_percentage', models.PositiveSmallIntegerField(blank=True, help_text='Discount percentage to give', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price of the product', max_digits=6, null=True)),
                ('discount_on', models.CharField(choices=[('product_count', 'Count'), ('cart_total', 'Total Value')], help_text='Discount based on count or total value of products', max_length=100)),
                ('discount_condition_value', models.PositiveSmallIntegerField(blank=True, help_text='Count of product or total valuefor discount to apply', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(blank=True, help_text='Product for which promotion applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'promotion_rule',
                'get_latest_by': 'created_at',
                'verbose_name_plural': 'Promotion Rules',
                'verbose_name': 'Promotion Rule',
            },
        ),
    ]
