# Generated by Django 2.2.15 on 2020-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_promotionrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionrule',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promotionrule',
            name='promotion_on',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount price of the product item', max_digits=6),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final price of the item after discount', max_digits=6),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='products',
            field=models.ManyToManyField(help_text='Products for which this promotion applies to', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='discount_on',
            field=models.CharField(choices=[('product_counts', 'Count'), ('total_value', 'Total Value')], help_text='Discount based on count or total value of products', max_length=100),
        ),
    ]
