# Generated by Django 2.2.15 on 2020-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200808_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount on cart', max_digits=6),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of all products on cart', max_digits=6),
        ),
    ]
