# Generated by Django 2.2.15 on 2020-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200808_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionrule',
            name='promotion_type',
            field=models.CharField(choices=[('discount_percentage', 'Discount Percentage on total ex: 10% offer'), ('fixed_discount_amount', 'Give fixed discount as product price ex: Rs 75 offer if bought 3'), ('product_fixed_price', 'Give product on a fixed price ex: Buy 3, Get it for Rs 75')], help_text='Type of promotion', max_length=100),
        ),
    ]
